# Generated by Django 4.0.2 on 2022-10-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='addTime',
        ),
    ]
