# Generated by Django 4.0.2 on 2022-10-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='add_date',
        ),
    ]
